### ISSUE TITLE
When using GraphingCalculator, I get the error "ReferenceError: Desmos is not defined"

### ISSUE THREAD

**Issue by danielfostiak** [ysulyma/desmos-react#5]
Any help would be appreciated? Really love this tool, I used it a year ago and it worked but revisiting it it is throwing this error now. I even downgraded the version to see if that would fix it but that was no good either?

**Comment by ysulyma** [comment]
You need to include Desmos separately
```html
<script src="https://www.desmos.com/api/v1.7/calculator.js?apiKey=dcb31709b452b1cf9dc26972add0fda6"></script>
```

**Comment by danielfostiak** [comment]
Thank you, I remember I did that last year. Thanks for the quick response, very much appreciated.
